### ISSUE TITLE
APi secret of token functionality

### ISSUE THREAD

**Issue by ViTuDia** [adamd9/Nightscout-MacOS-Menu-Bar#15]
My Nightscout is not visible public, how to enter a valid URL when there is a token or API secret needed to acces the Nightscout URL?

**Comment by adamd9** [comment]
Thanks @ViTuDia - yep I'll be working on this today.

**Comment by adamd9** [comment]
This is fixed @ViTuDia - just waiting on apple to approve

**Comment by adamd9** [comment]
Hey @ViTuDia ,

The new version supporting tokens is available for update:

<img width="989" alt="image" src="https://user-images.githubusercontent.com/4033496/188026673-b3f24830-de83-4382-b161-858977e8436d.png">

https://apps.apple.com/au/app/nightscout-menu-bar/id1639776072?mt=12




Enjoy!
