### ISSUE TITLE
response code was 401

### ISSUE THREAD

**Issue by benedicthenry** [adamd9/Nightscout-MacOS-Menu-Bar#19]
Firstly thank you for creating this Adam! I've entered my correct NS url and password in preferences, but am met with 'response code was 401' in the menu and [network] adjacent to the menu bar icon. Based on this, any ideas how I can get your app to work please?

**Comment by adamd9** [comment]
Hey @benedicthenry ! Usually 401 means "unauthorised", so it's probably something to do with the token. Can you please use the "report an issue" button in the menu and send me your NS url so I can debug?

<img width="510" alt="image" src="https://user-images.githubusercontent.com/4033496/188264002-aeb1a22c-3b5b-4a8a-bdfc-bf542a54ec7d.png">

**Comment by benedicthenry** [comment]
> Hey @benedicthenry ! Usually 401 means "unauthorised", so it's probably something to do with the token. Can you please use the "report an issue" button in the menu and send me your NS url so I can debug?
> 
> <img alt="image" width="510" src="https://user-images.githubusercontent.com/4033496/188264002-aeb1a22c-3b5b-4a8a-bdfc-bf542a54ec7d.png">

Thank you Adam, I have done so.

**Comment by adamd9** [comment]
Hey @benedicthenry , just confirming per our email that I'm not able to replicate this (your data shows fine in my instance).

If you (or anyone else) experience the same issue, please post screenshots of the exact error on screen along with screenshots of the settings page and I'll take a closer look.

**Comment by benedicthenry** [comment]
Hi Adam,

Thanks, it's still not working. I've just responded to your previous email
with the requested information and screenshots.

Best,

Benedict

**Comment by adamd9** [comment]
Thanks @benedicthenry for the additional info! Confirming that we worked out that it was the API_SECRET being provided, not a token - this was the reason for the 401. 

I will add some validation to check for the token pattern on the token input field, as I suspect others will do the same thing.

**Comment by adamd9** [comment]
fixed. will be in next app store submission
