### ISSUE TITLE
Unable to open preferences since updating to Ventura

### ISSUE THREAD

**Issue by heftychonker** [adamd9/Nightscout-MacOS-Menu-Bar#25]

**Comment by adamd9** [comment]
thanks @heftychonker, I'll update to Ventura today and check it out

**Comment by adamd9** [comment]
Hey @heftychonker, just waiting on apple to approve the submission.

**Comment by heftychonker** [comment]
Thanks @adamd9, much appreciated!

**Comment by adamd9** [comment]
Hey @heftychonker ! Closing this as the new version is approved and in the app store :-)
