### ISSUE TITLE
App crashes with no error

### ISSUE THREAD

**Issue by justinlulejian** [adamd9/Nightscout-MacOS-Menu-Bar#35]
I saw #28, but assumed this might be different due to the age of that issue. I recently upgraded to 13.3.1 and am on an apple silicon mac. The app shows "loading", then quits. I've attached two crash reports. The earlier on is attempting to open, and the later is attempting to open after deleting the app and reinstalling from the app store.

A little bit of googling is showing that this might be a manual breakpoint that was put into the code, a swift unrecoverable error, and/or the app needs to be rebuilt for the new version of macOS.
https://developer.apple.com/documentation/xcode/understanding-the-exception-types-in-a-crash-report#EXCBREAKPOINT-SIGTRAP-and-EXCBADINSTRUCTION-SIGILL
http://go/appledoc/xcode/addressing-crashes-from-swift-runtime-errors

[NSMB_crashes.zip](https://github.com/adamd9/Nightscout-MacOS-Menu-Bar/files/11369588/NSMB_crashes.zip)

**Comment by justinlulejian** [comment]
I'm thinking this is the latter issue (just needs a rebuild) since I was able to build the app locally in Xcode 14.3 and it launched successfully.

**Comment by adamd9** [comment]
Thanks @justinlulejian ! When the issue first presented, had you installed from the app store or had you just built it locally?

I'm not on 13.3.1 yet but I'll update this week and. take a better look

**Comment by justinlulejian** [comment]
I had installed from the App Store and confirmed I had the latest version
from there (no pending updates).

**Comment by adamd9** [comment]
Thanks @justinlulejian my Mac says it's up to date (but it's not on 13.3.1) - I think it's because it's a work-managed laptop. I might have to wait a few days before I can move to 13.3.1 and republish to the app store.

**Comment by adamd9** [comment]
Hey @justinlulejian ! Just letting you know I haven't forgotten about this - my Mac is work managed, and they aren't updating to 13.3.1 yet. I'm going to spin up a virtual instance and rebuild there :-)

**Comment by adamd9** [comment]
hey @justinlulejian , can you please try updating from the app store and see if it's now working for you?

**Comment by justinlulejian** [comment]
Looks like it's working for me on 13.4.1!
