### ISSUE TITLE
Keep crushing after last MAC update

### ISSUE THREAD

**Issue by yuvsketch** [adamd9/Nightscout-MacOS-Menu-Bar#46]
Keep crushing after last MAC update

![image](https://github.com/adamd9/Nightscout-MacOS-Menu-Bar/assets/75831100/afe79aec-75da-4570-a960-07e4d025c2c6)
![Screenshot 2023-11-22 at 20 42 22](https://github.com/adamd9/Nightscout-MacOS-Menu-Bar/assets/75831100/502a8ec5-d9a0-42ea-925d-420551fcb237)

**Comment by adamd9** [comment]
Hey @yuvsketch thanks for raising - as soon as I get my Mac updated I will test this. In the mean time, can you try removing the app and re-downloading?

**Comment by yuvsketch** [comment]
> Hey @yuvsketch thanks for raising - as soon as I get my Mac updated I will test this. In the mean time, can you try removing the app and re-downloading?

Hey, thanks
Yes I did, and I tried it once again..

**Comment by adamd9** [comment]
Hey @yuvsketch ! Let me know if https://github.com/adamd9/Nightscout-MacOS-Menu-Bar/releases/tag/2.5-rc2 fixes your crash too?

**Comment by yuvsketch** [comment]
Thank you!!

Can I download it from the appstore again? (like an update?)
(Its my work mac, so I can't install from zip)

**Comment by yuvsketch** [comment]
> Hey @yuvsketch ! Let me know if [`2.5-rc2` (release)](https://github.com/adamd9/Nightscout-MacOS-Menu-Bar/releases/tag/2.5-rc2) fixes your crash too?

Hey! Thanks for all the quick help and fixing...
Following the new update on appstore, It's still not working (+ I didn't had "update button" it had only "Open" so maybe I will need to wait 1 more day?) 
If not - can we maybe talk @ linkedin/facebook/mail? I will share the crash log and maybe you will understand what is the reason? 🙏

**Comment by yuvsketch** [comment]
> Hey @yuvsketch ! In the menu select "About..." and it should show you which version you're on:
> 
> <img alt="image" width="295" src="https://private-user-images.githubusercontent.com/4033496/289768344-12b467a5-ac69-4d39-8617-0ccc50045db2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzNjQwOTgsIm5iZiI6MTcwMjM2Mzc5OCwicGF0aCI6Ii80MDMzNDk2LzI4OTc2ODM0NC0xMmI0NjdhNS1hYzY5LTRkMzktODYxNy0wY2NjNTAwNDVkYjIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTJUMDY0OTU4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDlmODFkMjg2MGIwNjE5ZTA3MTc1YmU3MGM4ODgyZjNlNDQ4YThlOWVhNDNiMmRmYzMzZmY5MGUyMjU4YjY5ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ZPgnRRQWRbL0oKtJ18Nz-dBp44KPvUudP6JLp3on900">
> Yeah if you're on 2.5 and still experiencing an issue, choose "Report an issue" from the link and you can email me!

The app still crashing (not even want to open once) so I cant see the version I have..
What is your mail? I will send you the report
thank you!

**Comment by adamd9** [comment]
Ahh OK, yeah send it to [this email](mailto:adam@greatmachineinthesky.com).

**Comment by adamd9** [comment]
So the cause of this issue is this particular nightscout site doesn't return a timestamp in it's entries response. I'm not sure why, as there's no config option in Nightscout for that as far as I know. In any case, the unix epoc time is always returned for all, so I've switched my code to use this instead! 

I'll post in here once the new version is approved and in the app store

**Comment by adamd9** [comment]
New version is approved and in the App Store (wow, so fast!)!

**Comment by yuvsketch** [comment]
> New version is approved and in the App Store (wow, so fast!)!
> 
> 

Thank you!! 👑
I will try it in about an hour or two when I'll be at the office. 
And I will update of course.
